### PR TITLE
Fix english keyboard alt-PERIOD to be COLON

### PR DESCRIPTION
**Pull request by m-g-m**
Mapping fix to PERIOD key on vision English keypad.

### CODE REVIEW

**Comment by VladislavKoldobskiy** [comment]
Both yes and no. Russian HTC Vision keypads have comma instead on that button:
img_20140128_105227
The whole VisionKeypad purpose is to make possible to use two languages on a hardware keyboard. 
To use "default" WWE layout (if you don't need to switch languages), just uncheck all layouts in keyboard settings.

**Comment by m-g-m** [comment]
The WWE file mapping is incorrect as well.
Shouldn't the "English" layout match the "English" keyboard and not the "Russian" keyboard ?

**Comment by VladislavKoldobskiy** [comment]
Again, if you don't need to use language switching -- uncheck all layouts in keyboard settings. :)
"Default" layout will fall back to device-related key mapping (and use files that are in /system/usr/keylayout)
Anyway, I'll think about making VisionKeypad work for another keypad types, thanks for reminding.

**Comment by m-g-m** [comment]
OK, thx, will give it a shot next time I reflash. Going to post your advice on the forum.

**Comment by VladislavKoldobskiy** [comment]
Okay, so now selecting "English" in VisionKeypad will use WWE layout, which is now fixed.
I've also renamed an "English-for-russian-keypads" entry to a localized name, so now it should be fine for everyone.

**Comment by m-g-m** [comment]
Looks good, thanks.

**Pull request closed without merging**
